let iceCreamData = [
  {
    id: "ice-cream-1-valhalla-vanilla",
    name: "Valhalla Vanilla",
    price: 45,
    desc: "Embark on a legendary journey with this heavenly flavor fit for the gods. Creamy vanilla ice cream with swirls of ethereal delight, reminiscent of the mystical halls of Valhalla.",
    img: "images/img-1.jpg",
  },
  {
    id: "ice-cream-2-odins-cherry",
    name: "Odin's Cherry",
    price: 100,
    desc: "Savor the power of Odin with each cherry-infused bite. This flavor is as bold and captivating as the Allfather himself, with a burst of fruity sweetness that commands attention.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-3-thors-thunder-struck",
    name: "Thor's Thunder Struck",
    price: 25,
    desc: "Feel the electrifying energy of Thor's hammer with every lick. This explosive flavor combines tangy lemon sorbet with crackling pops of strawberry and a hint of mint, leaving you thunderstruck.",
    img: "images/img-3.jpg",
  },
  {
    id: "ice-cream-4-lokis-mischief-mint",
    name: "Loki's Mischief Mint",
    price: 300,
    desc: "Indulge in a mischievous delight with this minty flavor. The smooth mint ice cream swirls with swirls of chocolate fudge and unexpected surprises, just like the tricks and pranks of the infamous Loki.",
    img: "images/img-4.jpg",
  },
  {
    id: "ice-cream-5-freyjas-love-potion",
    name: "Freyja's Love Potion",
    price: 25,
    desc: "Fall under the spell of Freyja's enchanting flavor. This tantalizing blend of strawberry and rose petals will leave you feeling loved and bewitched, as if you've sipped from the goddess's own cup of love.",
    img: "images/img-5.png",
  },
  {
    id: "ice-cream-6-berserkers-bananas",
    name: "Berserker's Bananas",
    price: 200,
    desc: "Unleash your inner warrior with this wild and ferocious flavor. Creamy banana ice cream infused with crushed almonds and a hint of cinnamon, giving you the strength and energy of a true berserker.",
    img: "images/img-6.png",
  },
  {
    id: "ice-cream-7-valkyries-delight",
    name: "Valkyrie's Delight",
    price: 450,
    desc: "Be transported to the realm of the valiant with this delightful creation. A heavenly blend of lavender-infused honey ice cream and swirls of golden caramel, worthy of the most courageous warriors.",
    img: "images/img-7.png",
  },
  {
    id: "ice-cream-8-ragnarok-ripple",
    name: "Ragnarök Ripple",
    price: 45,
    desc: "Experience the chaos and harmony of the ultimate ice cream battle. This flavor combines creamy vanilla ice cream with a ripple of vibrant fruit flavors, symbolizing the clash of forces during Ragnarök.",
    img: "images/img-8.png",
  },
  {
    id: "ice-cream-9-shieldmaidens-strawberry",
    name: "Shieldmaiden's Strawberry",
    price: 85,
    desc: "Channel the fierce spirit of the shieldmaidens with this bold and empowering flavor. Juicy strawberries are blended with hints of black pepper, embodying the strength and grace of the warrior women.",
    img: "images/img-9.png",
  },
  {
    id: "ice-cream-10-frost-giants-cookie-dough",
    name: "Frost Giant's Cookie Dough",
    price: 120,
    desc: "Conquer the frozen lands with this mighty flavor. Creamy vanilla ice cream loaded with chunks of cookie dough and a touch of icy magic, reminiscent of the formidable Frost Giants.",
    img: "images/img-10.png",
  },
  {
    id: "ice-cream-11-viking-horned-melon",
    name: "Viking Horned Melon",
    price: 35,
    desc: "Embark on a daring journey with this exotic flavor. A refreshing melon sorbet infused with a hint of citrus, resembling the prized Viking helmets adorned with fierce horned emblems.",
    img: "images/img-11.png",
  },
  {
    id: "ice-cream-12-rune-inspired-rum-raisin",
    name: "Rune-Inspired Rum Raisin",
    price: 350,
    desc: "Unlock the ancient secrets with this mystic flavor. Creamy rum-infused ice cream with plump raisins, reminiscent of the runic inscriptions that held the wisdom of the Norse civilization.",
    img: "images/img-12.png",
  },
  {
    id: "ice-cream-13-skullcrusher-sundae",
    name: "Skullcrusher Sundae",
    price: 55,
    desc: "Prepare for a bone-chilling delight with this ice cream masterpiece. Rich chocolate ice cream with chunks of brownie and a swirl of blood-red cherry sauce, guaranteed to crush your cravings.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-14-longship-lime",
    name: "Longship Lime",
    price: 40,
    desc: "Embark on a zesty voyage with this refreshing lime sorbet. The tangy citrus flavor will transport you to the open seas, sailing on a Viking longship under the blazing sun.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-15-horned-honeycomb",
    name: "Horned Honeycomb",
    price: 65,
    desc: "Experience the sweetness of the gods with this indulgent honeycomb ice cream. Each creamy bite is filled with crunchy caramelized honey bits, reminiscent of mighty Viking helmets adorned with fierce horns.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-16-shield-wall-salted-caramel",
    name: "Shield Wall Salted Caramel",
    price: 75,
    desc: "Unite your taste buds with the strength of a Viking shield wall. Smooth salted caramel ice cream fortified with a fortress of crushed pretzels, creating a perfect balance of sweet and salty.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-17-thors-hammer-huckleberry",
    name: "Thor's Hammer Huckleberry",
    price: 95,
    desc: "Unleash the thunderous flavor of Thor's mighty hammer. This huckleberry-infused ice cream with swirls of thunderous blueberry sauce will electrify your senses with each heavenly bite.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-18-mead-madness",
    name: "Mead Madness",
    price: 85,
    desc: "Indulge in the frenzy of this intoxicating flavor. Creamy mead-infused ice cream swirled with ribbons of caramel and a touch of wildflower honey, capturing the spirit of Viking feasts.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-19-valkyries-victory",
    name: "Valkyrie's Victory",
    price: 120,
    desc: "Taste triumph with each spoonful of this victorious creation. A triumphant blend of vanilla and chocolate ice cream with golden caramel ribbons and a sprinkle of crunchy Viking helmet-shaped chocolate chips.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-20-fjord-fudge",
    name: "Fjord Fudge",
    price: 55,
    desc: "Sail along the chocolatey fjords with this delectable fudge ice cream. Swirls of rich fudge ripple through the creamy landscape, guiding your taste buds on a Viking-inspired adventure.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-21-berserkers-blueberry-blast",
    name: "Berserker's Blueberry Blast",
    price: 90,
    desc: "Unleash your inner berserker with this explosive blueberry flavor. The intensity of wild blueberries is unleashed in a frenzy of fruity goodness, leaving you energized and ready for battle.",
    img: "images/img-2.jpg",
  },
  {
    id: "ice-cream-22-runestone-rocky-road",
    name: "Runestone Rocky Road",
    price: 80,
    desc: "Decode the ancient flavors with this ice cream journey. Rich chocolate ice cream studded with chunks of marshmallow, almonds, and rune-shaped chocolate pieces, reminiscent of mysterious Viking runestones.",
    img: "images/img-2.jpg",
  },
];
